// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by scripts/fetch_tenant_config.dart
// Configured for tenant: carrefour (Carrefour)

import 'package:flutter/material.dart';
import 'config.dart';

const BrandConfig activeBrandConfig = BrandConfig(
  identity: BrandIdentity(
    appName: "Carrefour",
    tenantId: "carrefour",
    tagline: "Live more, spend less.",
    logoAssetPath: null,
    logoNetworkUrl: null,
  ),
  colors: BrandColors(
    primary: Color(0xFF004B87),
    onPrimary: Color(0xFFFFFFFF),
    secondary: Color(0xFFE30613),
    onSecondary: Color(0xFFFFFFFF),
    background: Color(0xFFF0F4F8),
    surface: Color(0xFFFFFFFF),
    surfaceContainer: Color(0xFFE4ECF4),
    onBackground: Color(0xFF001529),
    onSurface: Color(0xFF001529),
    onSurfaceVariant: Color(0xFF4A5568),
    error: Color(0xFFD32F2F),
    onError: Color(0xFFFFFFFF),
  ),
  typography: BrandTypography(
    displayFont: FontConfig(family: "Inter", source: FontSource.googleFont),
    bodyFont: FontConfig(family: "Inter", source: FontSource.googleFont),
    fontSizeScale: 1.0,
  ),
);
