// scripts/fetch_tenant_config.dart
import 'dart:convert';
import 'dart:io';

void main(List<String> args) async {
  String? tenantId;
  
  // Parse command-line args for --tenant, -t, or positional tenant ID
  for (int i = 0; i < args.length; i++) {
    if (args[i] == '--tenant' || args[i] == '-t') {
      if (i + 1 < args.length) {
        tenantId = args[i + 1];
        i++; // skip next arg
      }
    } else if (!args[i].startsWith('-')) {
      tenantId = args[i];
    }
  }

  if (tenantId == null || tenantId.trim().isEmpty || tenantId.trim().toLowerCase() == 'qless') {
    stdout.writeln('Info: No tenant ID specified or tenant is "qless". Generating default Qless configuration.');
    writeDefaultConfig();
    return;
  }

  tenantId = tenantId.trim();

  // Load environment variables from .env
  File envFile = File('.env');
  if (!envFile.existsSync()) {
    envFile = File('../.env');
  }
  if (!envFile.existsSync()) {
    stderr.writeln('Error: .env file not found. Falling back to default Qless configuration.');
    writeDefaultConfig();
    return;
  }

  final env = loadEnv(envFile.path);
  final supabaseUrl = env['SUPABASE_URL'];
  final supabaseAnonKey = env['SUPABASE_ANON_KEY'];

  if (supabaseUrl == null || supabaseUrl.isEmpty || supabaseAnonKey == null || supabaseAnonKey.isEmpty) {
    stderr.writeln('Error: SUPABASE_URL or SUPABASE_ANON_KEY not found in .env. Falling back to default Qless configuration.');
    writeDefaultConfig();
    return;
  }

  stdout.writeln('Fetching configuration for tenant: "$tenantId" from Supabase...');
  
  final tenantData = await fetchTenantConfig(supabaseUrl, supabaseAnonKey, tenantId);
  if (tenantData == null) {
    stderr.writeln('Warning: Failed to fetch tenant "$tenantId". Falling back to default Qless configuration.');
    writeDefaultConfig();
    return;
  }

  if (tenantData['is_active'] == false) {
    stderr.writeln('Warning: Tenant "$tenantId" is marked as inactive. Falling back to default Qless configuration.');
    writeDefaultConfig();
    return;
  }

  try {
    writeTenantConfig(tenantData);
    stdout.writeln('Success: Generated configuration for tenant "$tenantId" in lib/config/active_tenant.g.dart.');
  } catch (e) {
    stderr.writeln('Error generating tenant config file: $e. Falling back to default Qless configuration.');
    writeDefaultConfig();
  }
}

Map<String, String> loadEnv(String path) {
  final file = File(path);
  if (!file.existsSync()) return {};
  final lines = file.readAsLinesSync();
  final env = <String, String>{};
  for (var line in lines) {
    line = line.trim();
    if (line.isEmpty || line.startsWith('#')) continue;
    final idx = line.indexOf('=');
    if (idx == -1) continue;
    final key = line.substring(0, idx).trim();
    var val = line.substring(idx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.substring(1, val.length - 1);
    }
    env[key] = val;
  }
  return env;
}

Future<Map<String, dynamic>?> fetchTenantConfig(String url, String anonKey, String tenantId) async {
  final client = HttpClient();
  try {
    final cleanUrl = url.endsWith('/') ? url.substring(0, url.length - 1) : url;
    final uri = Uri.parse('$cleanUrl/rest/v1/tenants?tenant_id=eq.$tenantId&select=*');
    final request = await client.getUrl(uri);
    
    request.headers.add('apikey', anonKey);
    request.headers.add('Authorization', 'Bearer $anonKey');
    
    final response = await request.close();
    if (response.statusCode != 200) {
      stderr.writeln('Supabase HTTP Error: ${response.statusCode}');
      final body = await response.transform(utf8.decoder).join();
      stderr.writeln('Response Body: $body');
      return null;
    }
    
    final body = await response.transform(utf8.decoder).join();
    final List<dynamic> data = json.decode(body);
    if (data.isEmpty) {
      stderr.writeln('No record found in "tenants" table with tenant_id = "$tenantId"');
      return null;
    }
    return data.first as Map<String, dynamic>;
  } catch (e) {
    stderr.writeln('Network error querying Supabase: $e');
    return null;
  } finally {
    client.close();
  }
}

void writeDefaultConfig() {
  final file = File('lib/config/active_tenant.g.dart');
  const content = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by scripts/fetch_tenant_config.dart
// Defaulted to Qless Theme

import 'package:flutter/material.dart';
import 'config.dart';

final BrandConfig activeBrandConfig = BrandConfig.qless();
''';
  file.writeAsStringSync(content);
}

void writeTenantConfig(Map<String, dynamic> tenant) {
  final file = File('lib/config/active_tenant.g.dart');
  
  final appName = tenant['app_name'] ?? 'Qless';
  final tenantId = tenant['tenant_id'] ?? 'qless';
  final tagline = tenant['tagline'];
  final logoAssetPath = tenant['logo_asset_path'];
  final logoNetworkUrl = tenant['logo_network_url'];
  
  // Helper to format colors
  String col(String? val, String defaultColorHex) {
    if (val == null || val.trim().isEmpty) {
      return 'Color(0x$defaultColorHex)';
    }
    var clean = val.replaceAll('#', '').trim().toUpperCase();
    if (clean.length == 6) {
      return 'Color(0xFF$clean)';
    } else if (clean.length == 8) {
      return 'Color(0x$clean)';
    }
    return 'Color(0x$defaultColorHex)';
  }

  // Helper to format font source
  String fontSource(String? source) {
    if (source == null) return 'FontSource.asset';
    final lower = source.toLowerCase();
    if (lower.contains('google')) {
      return 'FontSource.googleFont';
    }
    return 'FontSource.asset';
  }

  final double fontSizeScale = double.tryParse(tenant['font_size_scale']?.toString() ?? '') ?? 1.00;

  final content = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by scripts/fetch_tenant_config.dart
// Configured for tenant: $tenantId ($appName)

import 'package:flutter/material.dart';
import 'config.dart';

const BrandConfig activeBrandConfig = BrandConfig(
  identity: BrandIdentity(
    appName: ${json.encode(appName)},
    tenantId: ${json.encode(tenantId)},
    tagline: ${tagline != null ? json.encode(tagline) : 'null'},
    logoAssetPath: ${logoAssetPath != null ? json.encode(logoAssetPath) : 'null'},
    logoNetworkUrl: ${logoNetworkUrl != null ? json.encode(logoNetworkUrl) : 'null'},
  ),
  colors: BrandColors(
    primary: ${col(tenant['color_primary'], 'FF001A23')},
    onPrimary: ${col(tenant['color_on_primary'], 'FFFFFFFF')},
    secondary: ${col(tenant['color_secondary'], 'FFB3EFB2')},
    onSecondary: ${col(tenant['color_on_secondary'], 'FF001A23')},
    background: ${col(tenant['color_background'], 'FFE8F1F2')},
    surface: ${col(tenant['color_surface'], 'FFFFFFFF')},
    surfaceContainer: ${col(tenant['color_surface_container'], 'FFE8F1F2')},
    onBackground: ${col(tenant['color_on_background'], 'FF001A23')},
    onSurface: ${col(tenant['color_on_surface'], 'FF001A23')},
    onSurfaceVariant: ${col(tenant['color_on_surface_variant'], 'FF4A5568')},
    error: ${col(tenant['color_error'], 'FFEF4444')},
    onError: ${col(tenant['color_on_error'], 'FFFFFFFF')},
  ),
  typography: BrandTypography(
    displayFont: FontConfig(
      family: ${json.encode(tenant['display_font_family'] ?? 'ClashDisplay')},
      source: ${fontSource(tenant['display_font_source'])},
    ),
    bodyFont: FontConfig(
      family: ${json.encode(tenant['body_font_family'] ?? 'ClashGrotesk')},
      source: ${fontSource(tenant['body_font_source'])},
    ),
    fontSizeScale: $fontSizeScale,
  ),
);
''';
  file.writeAsStringSync(content);
}
