name: Sync to Hugging Face Space

on:
  push:
    branches: [ shravan, main ]
    paths:
      - 'hf_server/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for subtree split

      - name: Push subtree to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          # Split the subtree and force push the resulting commit history to Hugging Face Space
          git push https://Mojo-Maniac:$HF_TOKEN@huggingface.co/spaces/Mojo-Maniac/AIShoppingAssistance_Server $(git subtree split --prefix=hf_server ${{ github.ref_name }}):main --force
