-- 1. Create the inventory table
CREATE TABLE IF NOT EXISTS public.inventory (
  sku TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  price_rupees NUMERIC NOT NULL,
  staging_dirs TEXT[] NOT NULL,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable row level security (optional, but recommended)
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.inventory FOR SELECT USING (true);

-- 2. Insert items
INSERT INTO public.inventory (sku, slug, name, price_rupees, staging_dirs, image_url)
VALUES
  ('QLS-0001', '5-star-magic-health-drink-bournvita', 'Bournvita 5 Star Magic Health Drink', 249, ARRAY['5-star-magic-health-drink-bournvita'], 'https://tse4.mm.bing.net/th/id/OIP.CfD6TJyGaP4UXqygLu37MgHaHa?w=200&h=200&c=7'),
  ('QLS-0002', 'air-freshener-ambi-pur', 'Ambi Pur Air Freshener', 299, ARRAY['air-freshener-ambi-pur'], 'https://thfvnext.bing.com/th/id/OIP.CL9GZsmqZEL5l11WPo5omwHaL2?w=200&h=200&c=7'),
  ('QLS-0003', 'almond-chocolate-bar-snickers', 'Snickers Almond Chocolate Bar', 50, ARRAY['almond-chocolate-bar-snickers'], 'https://tse3.mm.bing.net/th/id/OIP.x0BU5YgeYgwfWE20BZSSnQHaD6?w=200&h=200&c=7'),
  ('QLS-0004', 'american-style-cream-and-onion-chips-lays', 'Lay''s American Style Cream and Onion Chips', 20, ARRAY['american-style-cream-and-onion-chips-lays', 'american-style-cream-and-onion-chips-lays-2', 'american-style-cream-and-onion-chips-lays-3', 'american-style-cream-and-onion-chips-lays-4'], 'https://tse4.mm.bing.net/th/id/OIP.kvh9Ch5lBiA7svaKpHRzbQAAAA?w=200&h=200&c=7'),
  ('QLS-0005', 'car-air-freshener-jasmine-ambi-pur', 'Ambi Pur Jasmine Car Air Freshener', 399, ARRAY['car-air-freshener-jasmine-ambi-pur'], 'https://thf.bing.com/th/id/OIP.yfjG7J5GzbKQd4wnOlSn3wHaHa?w=200&h=200&c=7'),
  ('QLS-0006', 'ceregrow-multigrain-cereal-nestle', 'Nestle Ceregrow Multigrain Cereal', 365, ARRAY['ceregrow-multigrain-cereal-nestle', 'ceregrow-multigrain-cereal-nestle-2'], 'https://thf.bing.com/th/id/OIP.XjG0CSlm95W8rhsWDk0fIAHaHF?w=200&h=200&c=7'),
  ('QLS-0007', 'cerelac-rice-nestle', 'Nestle Cerelac Rice', 285, ARRAY['cerelac-rice-nestle'], 'https://tse4.mm.bing.net/th/id/OIP.fxo2y7tSDPS1QxOx336P0QHaEx?w=200&h=200&c=7'),
  ('QLS-0008', 'cerelac-wheat-apple-nestle', 'Nestle Cerelac Wheat Apple', 325, ARRAY['cerelac-wheat-apple-nestle'], 'https://thf.bing.com/th/id/OIP.8TYsIopnk3Mx2fA8fdDoMAHaJv?w=200&h=200&c=7'),
  ('QLS-0009', 'cheez-puffs-cheetos', 'Cheetos Cheez Puffs', 20, ARRAY['cheez-puffs-cheetos', 'cheez-puffs-cheetos-2'], 'https://tse1.mm.bing.net/th/id/OIP.h1QxUYJ22bkr__X3SCuN7AHaEK?w=200&h=200&c=7'),
  ('QLS-0010', 'chicken-noodles-maggi', 'Maggi Chicken Noodles', 15, ARRAY['chicken-noodles-maggi'], 'https://thf.bing.com/th/id/OIP.yLaqqLTolSld-S6c4CMnPQHaHa?w=200&h=200&c=7'),
  ('QLS-0011', 'chocolate-bar-mars', 'Mars Chocolate Bar', 40, ARRAY['chocolate-bar-mars'], 'https://thf.bing.com/th/id/OIP.MYbhkzy0SgUx8qNF0EO9XAAAAA?w=200&h=200&c=7'),
  ('QLS-0012', 'chocolate-bar-snickers', 'Snickers Chocolate Bar', 40, ARRAY['chocolate-bar-snickers'], 'https://thf.bing.com/th/id/OIP.5yJz6dS-BCwk_u2zr4hjvQHaEo?w=200&h=200&c=7'),
  ('QLS-0013', 'chocolate-bar-softer-bar', 'Softer Bar Chocolate Bar', 30, ARRAY['chocolate-bar-softer-bar'], 'https://tse3.mm.bing.net/th/id/OIP.mgFzKa37Kp6pOprZ9U7-yQHaE8?w=200&h=200&c=7'),
  ('QLS-0014', 'chocos-crunchy-bites-coco-caramel-kelloggs', 'Kellogg''s Chocos Crunchy Bites Coco Caramel', 35, ARRAY['chocos-crunchy-bites-coco-caramel-kelloggs'], 'https://thfvnext.bing.com/th/id/OIP.EZOmGA0UTMTn9I5k1i7kWgHaHa?w=200&h=200&c=7'),
  ('QLS-0015', 'classic-malt-health-drink-horlicks', 'Horlicks Classic Malt Health Drink', 249, ARRAY['classic-malt-health-drink-horlicks'], 'https://thf.bing.com/th/id/OIP.zZU_XDuh3CjzPnMwjiJ-bAHaJ4?w=200&h=200&c=7'),
  ('QLS-0016', 'corn-flakes-original-kelloggs', 'Kellogg''s Corn Flakes Original', 195, ARRAY['corn-flakes-original-kelloggs', 'corn-flakes-original-kelloggs-2'], 'https://tse4.mm.bing.net/th/id/OIP.4TaH3WMgB7gofYGivMkguAHaDt?w=200&h=200&c=7'),
  ('QLS-0017', 'dairy-milk-chocolate-cadbury', 'Cadbury Dairy Milk Chocolate', 40, ARRAY['dairy-milk-chocolate-cadbury'], 'https://thfvnext.bing.com/th/id/OIP.9RGu2eO01uw2sAaWU_vYjAHaE8?w=200&h=200&c=7'),
  ('QLS-0018', 'dairy-milk-crispello-cadbury', 'Cadbury Dairy Milk Crispello', 40, ARRAY['dairy-milk-crispello-cadbury'], 'https://tse4.mm.bing.net/th/id/OIP.kvh9Ch5lBiA7svaKpHRzbQAAAA?w=200&h=200&c=7'),
  ('QLS-0019', 'dairy-milk-roast-almond-cadbury', 'Cadbury Dairy Milk Roast Almond', 50, ARRAY['dairy-milk-roast-almond-cadbury'], 'https://thf.bing.com/th/id/OIP.kW1bXcJt8M8RnrGD2uYB3QHaE7?w=200&h=200&c=7'),
  ('QLS-0020', 'disinfectant-surface-cleaner-lizol', 'Lizol Disinfectant Surface Cleaner', 220, ARRAY['disinfectant-surface-cleaner-lizol'], 'https://tse1.mm.bing.net/th/id/OIP.y7eiSOpiFyf9U0mHV-B0PAHaLH?w=200&h=200&c=7'),
  ('QLS-0021', 'flushmatic-citrus-toilet-cleaner-harpic', 'Harpic Flushmatic Citrus Toilet Cleaner', 99, ARRAY['flushmatic-citrus-toilet-cleaner-harpic'], 'https://tse1.mm.bing.net/th/id/OIP.79VnC-PkVR1Csyv2NgQ6xwHaKd?w=200&h=200&c=7'),
  ('QLS-0022', 'fuse-chocolate-bar-cadbury', 'Cadbury Fuse Chocolate Bar', 40, ARRAY['fuse-chocolate-bar-cadbury'], 'https://tse4.mm.bing.net/th/id/OIP.txrG5wZqgcaQ75lReIAFfAHaFj?w=200&h=200&c=7'),
  ('QLS-0023', 'ginger-garlic-paste-aachi', 'Aachi Ginger Garlic Paste', 80, ARRAY['ginger-garlic-paste-aachi'], 'https://tse1.mm.bing.net/th/id/OIP.FkM0DWr6eXUsaSmlISsE0AHaKl?w=200&h=200&c=7'),
  ('QLS-0024', 'gold-standardised-milk-amul', 'Amul Gold Standardised Milk', 37, ARRAY['gold-standardised-milk-amul'], 'https://thf.bing.com/th/id/OIP.FnFsD9_ZZPcLTUE_ENYCGQHaE8?w=200&h=200&c=7'),
  ('QLS-0025', 'groundnut-oil-idhayam-mantra', 'Idhayam Mantra Groundnut Oil', 250, ARRAY['groundnut-oil-idhayam-mantra'], 'https://tse3.mm.bing.net/th/id/OIP.z-jYbF4K25x5MmCpZNGEkgHaD7?w=200&h=200&c=7'),
  ('QLS-0026', 'health-drink-2x-strength-bournvita', 'Bournvita 2x Strength Health Drink', 275, ARRAY['health-drink-2x-strength-bournvita'], 'https://thfvnext.bing.com/th/id/OIP.VndW83oMDeZSRGmPwwBNzAHaFW?w=200&h=200&c=7'),
  ('QLS-0027', 'health-drink-boost', 'Boost Health Drink', 255, ARRAY['health-drink-boost', 'health-drink-boost-2', 'health-drink-boost-3'], 'https://thfvnext.bing.com/th/id/OIP.yR4WmF6VzWp4f8s49ZZcCQHaEK?w=200&h=200&c=7'),
  ('QLS-0028', 'hot-and-spicy-korean-kimchi-noodles-geki', 'Geki Hot and Spicy Korean Kimchi Noodles', 50, ARRAY['hot-and-spicy-korean-kimchi-noodles-geki'], 'https://tse2.mm.bing.net/th/id/OIP.aZ9qS7FHcFFy1WT8fppcsgHaE7?w=200&h=200&c=7'),
  ('QLS-0029', 'hot-and-sweet-tomato-chilli-sauce-maggi', 'Maggi Hot and Sweet Tomato Chilli Sauce', 170, ARRAY['hot-and-sweet-tomato-chilli-sauce-maggi'], 'https://tse2.mm.bing.net/th/id/OIP.UWBY4Q5uab27rSd1AERe_wHaFO?w=200&h=200&c=7'),
  ('QLS-0030', 'indias-magic-masala-chips-lays', 'Lay''s India''s Magic Masala Chips', 20, ARRAY['indias-magic-masala-chips-lays', 'indias-magic-masala-chips-lays-2'], 'https://thf.bing.com/th/id/OIP.EFTTfq6Jfn_O3H9jYEysLwHaFj?w=200&h=200&c=7'),
  ('QLS-0031', 'jasmine-mist-air-freshener-odonil', 'Odonil Jasmine Mist Air Freshener', 99, ARRAY['jasmine-mist-air-freshener-odonil'], 'https://thfvnext.bing.com/th/id/OIP.VSQRtnRyq1W3GUhBS-53vAHaJf?w=200&h=200&c=7'),
  ('QLS-0032', 'kitkat-chunky-white-nestle', 'Nestle KitKat Chunky White', 70, ARRAY['kitkat-chunky-white-nestle'], 'https://tse1.mm.bing.net/th/id/OIP.aaXFTkx92jAO_ZzgZT_FFAHaHG?w=200&h=200&c=7'),
  ('QLS-0033', 'lactogen-pro-1-nestle', 'Nestle Lactogen Pro 1', 420, ARRAY['lactogen-pro-1-nestle'], 'https://tse1.mm.bing.net/th/id/OIP.s0YKhFDn9S_VHOt93w6A_AHaFj?w=200&h=200&c=7'),
  ('QLS-0034', 'lactogen-pro-4-nestle', 'Nestle Lactogen Pro 4', 440, ARRAY['lactogen-pro-4-nestle'], 'https://tse4.mm.bing.net/th/id/OIP.4A--jfye6aU-bw0xqkuGYgHaGL?w=200&h=200&c=7'),
  ('QLS-0035', 'milkybar-white-chocolate-nestle', 'Nestle Milkybar White Chocolate', 20, ARRAY['milkybar-white-chocolate-nestle'], 'https://thfvnext.bing.com/th/id/OIP.KRqpMiam5r4j6yWldnSIzQHaEK?w=200&h=200&c=7'),
  ('QLS-0036', 'multigrain-chocos-chhota-bheem-kelloggs', 'Kellogg''s Multigrain Chocos Chhota Bheem', 20, ARRAY['multigrain-chocos-chhota-bheem-kelloggs'], 'https://thf.bing.com/th/id/OIP.0_YDmWYZ2FqB7ksJVuKaiAHaFj?w=200&h=200&c=7'),
  ('QLS-0037', 'multigrain-chocos-kelloggs', 'Kellogg''s Multigrain Chocos', 210, ARRAY['multigrain-chocos-kelloggs'], 'https://thf.bing.com/th/id/OIP.NCWImztcRiRqM_Ru99UnNAHaE8?w=200&h=200&c=7'),
  ('QLS-0038', 'oats-quaker', 'Quaker Oats', 195, ARRAY['oats-quaker'], 'https://tse2.mm.bing.net/th/id/OIP.VhVglY8GsLYgBiAhsjbrgwAAAA?w=200&h=200&c=7'),
  ('QLS-0039', 'power-pocket-rose-fresh-blossom-godrej-aer', 'Godrej Aer Power Pocket Rose Fresh Blossom', 65, ARRAY['power-pocket-rose-fresh-blossom-godrej-aer'], 'https://tse3.mm.bing.net/th/id/OIP.u-s-xxB9oa4AUp-w97yoGwHaJ4?w=200&h=200&c=7'),
  ('QLS-0040', 'puffcorn-yummy-cheese-kurkure-playz', 'Kurkure Playz Puffcorn Yummy Cheese', 20, ARRAY['puffcorn-yummy-cheese-kurkure-playz'], 'https://tse4.mm.bing.net/th/id/OIP.QE0DroidjeH9B4rJIoX64gHaHa?w=200&h=200&c=7'),
  ('QLS-0041', 'refined-sunflower-oil-gold-winner', 'Gold Winner Refined Sunflower Oil', 180, ARRAY['refined-sunflower-oil-gold-winner'], 'https://tse4.mm.bing.net/th/id/OIP.C5RS0ayqcd5XqcGpp2qeZQHaE7?w=200&h=200&c=7'),
  ('QLS-0042', 'rich-tomato-ketchup-maggi', 'Maggi Rich Tomato Ketchup', 155, ARRAY['rich-tomato-ketchup-maggi'], 'https://thf.bing.com/th/id/OIP.NvNf9XuP3l9JtQiuSndfuQHaHa?w=200&h=200&c=7'),
  ('QLS-0043', 'rolled-oats-disaano', 'Disaano Rolled Oats', 199, ARRAY['rolled-oats-disaano'], 'https://tse2.mm.bing.net/th/id/OIP.9tN6FWNZlYwO9qfLlYG7YAHaEG?w=200&h=200&c=7'),
  ('QLS-0044', 'room-spray-odonil', 'Odonil Room Spray', 179, ARRAY['room-spray-odonil'], 'https://tse4.mm.bing.net/th/id/OIP.UG2C8I2uwLCfXbUvmEGDHgHaFx?w=200&h=200&c=7'),
  ('QLS-0045', 'shampoo-hair-colour-godrej-selfie', 'Godrej Selfie Shampoo Hair Colour', 30, ARRAY['shampoo-hair-colour-godrej-selfie'], 'https://thfvnext.bing.com/th/id/OIP.YYxfFSVknp7HwWAPyoaQrQHaHa?w=200&h=200&c=7'),
  ('QLS-0046', 'similac-classic-stage-1-abbott', 'Abbott Similac Classic Stage 1', 430, ARRAY['similac-classic-stage-1-abbott'], 'https://tse1.mm.bing.net/th/id/OIP.r4vkGLFsm0jnIWPdhcoTiQHaD1?w=200&h=200&c=7'),
  ('QLS-0047', 'spanish-tomato-tango-chips-lays', 'Lay''s Spanish Tomato Tango Chips', 20, ARRAY['spanish-tomato-tango-chips-lays', 'spanish-tomato-tango-chips-lays-2'], 'https://tse2.mm.bing.net/th/id/OIP.ZOKDIqgvpjWWPGzGihn6bwHaKd?w=200&h=200&c=7'),
  ('QLS-0048', 'spicy-manchurian-cuppa-noodles-maggi', 'Maggi Spicy Manchurian Cuppa Noodles', 50, ARRAY['spicy-manchurian-cuppa-noodles-maggi'], 'https://tse4.mm.bing.net/th/id/OIP.UvTLwKwzcQOTtzTkl7yN7wHaLH?w=200&h=200&c=7'),
  ('QLS-0049', 'super-muesli-zero-added-sugar-yoga-bar', 'Yoga Bar Super Muesli Zero Added Sugar', 349, ARRAY['super-muesli-zero-added-sugar-yoga-bar'], 'https://tse4.mm.bing.net/th/id/OIP.RddT7RakFiiwp8ysI2vH0QHaI1?w=200&h=200&c=7'),
  ('QLS-0050', 'sweet-chilli-hot-sauce-veeba', 'Veeba Sweet Chilli Hot Sauce', 149, ARRAY['sweet-chilli-hot-sauce-veeba'], 'https://tse1.mm.bing.net/th/id/OIP.7HTg2QaNljg1UJM5XhoFkwHaNK?w=200&h=200&c=7'),
  ('QLS-0051', 'sweet-onion-sauce-veeba', 'Veeba Sweet Onion Sauce', 149, ARRAY['sweet-onion-sauce-veeba'], 'https://thf.bing.com/th/id/OIP.PvJDo_gkME3Vv4dkPAryMwAAAA?w=200&h=200&c=7'),
  ('QLS-0052', 'synthetic-vinegar-double-horse', 'Double Horse Synthetic Vinegar', 55, ARRAY['synthetic-vinegar-double-horse'], 'https://tse1.mm.bing.net/th/id/OIP.awAd4HZVXQK7wWft8SEShwAAAA?w=200&h=200&c=7'),
  ('QLS-0053', 'taj-mahal-tea-brooke-bond', 'Brooke Bond Taj Mahal Tea', 260, ARRAY['taj-mahal-tea-brooke-bond'], 'https://tse2.mm.bing.net/th/id/OIP.5X_VYOLhZuByJxRVOCjVfQHaF7?w=200&h=200&c=7'),
  ('QLS-0054', 'thermosteel-water-bottle-milton', 'Milton Thermosteel Water Bottle', 899, ARRAY['thermosteel-water-bottle-milton'], 'https://thfvnext.bing.com/th/id/OIP.RuS1LuBVnVt8VhWS7fnQOQHaHa?w=200&h=200&c=7'),
  ('QLS-0055', 'tomato-sauce-happy', 'Happy Tomato Sauce', 110, ARRAY['tomato-sauce-happy'], 'https://tse3.mm.bing.net/th/id/OIP.nWdrabpB-WrPuttfzFTxYwHaDl?w=200&h=200&c=7'),
  ('QLS-0056', 'womens-plus-caramel-horlicks', 'Horlicks Women''s Plus Caramel', 320, ARRAY['womens-plus-caramel-horlicks', 'womens-plus-caramel-horlicks-2'], 'https://tse2.mm.bing.net/th/id/OIP.Cqmz22r29Fdo9yXBhH6kWgHaNJ?w=200&h=200&c=7');